# Generated by Django 4.2.7 on 2026-02-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='plant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrecord',
            name='alert_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentrecord',
            name='has_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_alerts', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_api.equipmentdataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('predicted_value', models.FloatField()),
                ('confidence', models.FloatField()),
                ('prediction_date', models.DateField()),
                ('trend', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_api.equipmentdataset')),
                ('equipment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_api.equipmentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DataValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.IntegerField()),
                ('missing_values', models.IntegerField(default=0)),
                ('duplicate_records', models.IntegerField(default=0)),
                ('outliers_count', models.IntegerField(default=0)),
                ('quality_score', models.FloatField()),
                ('validation_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipment_api.equipmentdataset')),
            ],
        ),
        migrations.CreateModel(
            name='DataComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='equipment_api.equipmentdataset')),
                ('dataset2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='equipment_api.equipmentdataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_api.equipmentdataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_datasets', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dataset', 'shared_with')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('flowrate', 'Flowrate'), ('pressure', 'Pressure'), ('temperature', 'Temperature')], max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'parameter')},
            },
        ),
    ]
