# Generated by Django 4.2.7 on 2026-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_api', '0002_equipmentdataset_plant_equipmentdataset_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='categorical_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='parameter_averages',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='parameter_columns',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='equipmentrecord',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_flowrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='avg_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdataset',
            name='type_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='flowrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrecord',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
